### PR TITLE
Feature - expand all rows

### PR DESCRIPTION
**Pull request by ian-mcdowell**
Added a method to expand all rows. This removes the need to loop through and call expandRowForItem: on each root item. The method does everything in one batch update, making it much faster than looping as well, based on my testing.

Also added a method to expand all rows with a RATreeViewRowAnimation as a parameter. The other method uses the default expand animation.

### CODE REVIEW

**Comment by IMcD23** [comment]
Any chance this could get merged in? Any thoughts/concerns?

**Comment by Augustyniak** [comment]
@IMcD23 Thanks for PR :+1: 

I like the idea of the PR but I would modify the public API that is provided by it. I think that we should expand functionality of the `expandRowForItem:`, `expandRowForItem:withRowAnimation:` and `expandRowForItem:expandChildren:withRowAnimation:` (also modify collapse methods so they works for `item` equal to `nil`) methods so that all tree can be expanded if we pass `nil` as `item` and `YES` and `expandChildren` parameter. That would allow us to keep the public API in its current state.

What do you think about that idea?

**Comment by IMcD23** [comment]
I like that idea. I'll take a look into adding the ability to put in a nil item into the expand and collapse methods. That only makes sense to me, however, as an additional way of doing it. I feel as if most people won't think that passing a nil tree node to expand will actually mean to expand *every* tree node.

It's up to you with what way you want to do, but I think it would probably work best to either allow both ways, or just the way I have in this PR.

Also, I think no matter what, the `expandsChildrenOnLoad` property should be kept. This allows the user to have it always expand without calling any additional functions.

**Comment by Maxatma** [comment]
So this functionality isn't added? Why Is this closed? How to expand all rows at start?

**Pull request closed without merging**
