### PR TITLE
Fix duplicate cells bug

### LINKED ISSUE #105: A bug problem about - (void)expandRowForItem:(id)item
When I call this function “- (void)expandRowForItem:(id)item”， the cell number doubled。 The old cell still retained。 But in v0.9.2 is OK @Augustyniak

### PR DESCRIPTION
**Pull request by Fogh**
Seems like a missing exclamation mark was causing the bug. 

Fixes #105 for me.

### CODE REVIEW

**Comment by abbasmousavi** [comment]
+1 for this pull request

**Comment by Augustyniak** [comment]
This PR breaks collapsing of the cells. After cell is collapsed you have to tap twice to expand it again.

**Comment by Fogh** [comment]
I'm using this fix in an app. I have no problem with expanding rows. They expand on first tap.

**Comment by Augustyniak** [comment]
What about test project? I tried your fixed there and the results are as I described.

**Comment by Fogh** [comment]
You're right. It doesn't seem to work in the test project. That is stange, since I used the test project to implement it in the app where I have it working.

**Comment by abbasmousavi** [comment]
I have the same problem with the fix, when I use the fix, I should tap three time on a once collapsed item to expand it.

**Comment by gtgg** [comment]
This problem still in 1.0.2

**Comment by Fogh** [comment]
The problem still occurs in 1.0.2 for me as well.

**Comment by Augustyniak** [comment]
The problem is that the test project works fine for me. 
@Fogh @gtgg  Ok, can you provide me with more information? Do you use swift or objective-c? Any big differences between the way test project uses `RATreeView` and the way your projects uses it?

**Comment by abbasmousavi** [comment]
This duplicate effect can happen if you generate new object every time ratreeview asks you for children of a specific item. Ratreeview uses address of objects so every time you should provide exact same objects. @fog @gtgg

**Comment by Augustyniak** [comment]
@abbasmousavi That's a good point :+1:

**Comment by gtgg** [comment]
@abbasmousavi  you are right.But I can't provide exact same objects。

**Comment by Fogh** [comment]
@abbasmousavi You are right! I load data from a SQLite database, so I don't use the same objects.

**Comment by gtgg** [comment]
@Augustyniak  @Fogh  i can't provide exact same objects. I get children of specific item from net. RATreeView is work-well on 0.9.2。 So, i still need some help to fix this problem,please.

**Comment by Augustyniak** [comment]
@Fogh @gtgg @abbasmousavi Version 1.0.3 has been released. It should fix the problem with duplicated cells even if provided objects change between collapse/expand operations.

Please let me know whether new version behave correctly in your cases.

**Comment by abbasmousavi** [comment]
@Augustyniak, I provide same objects every time and yes, 1.0.3 behaves correctly in my case. Thanks for the update.

**Pull request closed without merging**
