### PR TITLE
RATreeNodeController index caching

### PR DESCRIPTION
**Pull request by fins**
fix for performance problem discussed in issue 79

### CODE REVIEW

**Comment by victorbitca** [comment]
@Augustyniak Could you please review this fork, it contains some nice performance optimisations for big tree views. :shipit:

**Comment by OlegAnghelov** [comment]
@Augustyniak Please do, we really need these changes, and please make a new pod version after. If you don't have time, please notify us, we will be glad to help.

**Comment by Augustyniak** [comment]
Hey,
Sorry for really long response time. New version od library will be released within a few days - it will contain mainly performance improvements..

**Comment by Augustyniak** [comment]
Version 1.0.0 was released today. I decided to implement my own approach as the one suggested in this PR didn't solve all issues.

I hope it will help.

**Pull request closed without merging**
